//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public class LDZCas
    {
        public int LDZCaseId { get; set; }
        public Nullable<int> CaseId { get; set; }
        public string EmailId { get; set; }
        public string IncidentType { get; set; }
        public string IncidentDescription { get; set; }
        public Nullable<int> ServiceId { get; set; }
        public string Location { get; set; }
        public string CustomerPhone { get; set; }
        public string ProviderName { get; set; }
        public string CaseStatus { get; set; }
    
        public virtual Case Case { get; set; }
        public virtual Service Service { get; set; }
        public virtual ODZUser ODZUser { get; set; }
    }
}
